### PR TITLE
add dependabot

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your app.
I made some minor edits.
I hope they are useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by hannesbraun** [comment]
I don't think I need to enable Dependabot for this project. Especially since this repository will move its main hosting location to SourceHut (https://git.sr.ht/~hannes/ayaya) soon and Dependabot won't be available there anyway.

If you have a specific problem though, which would be fixed with an updated dependency, just let me know and I'll update the dependency and make a new release.

**Comment by theavege** [comment]
If it's not a secret, why are you moving this repository to SourceHut?

**Comment by hannesbraun** [comment]
For me, there are two main reasons:
- I started to prefer SourceHut for its simplicity, explicit absence of certain features (such as stars on GitHub) and the email-driven workflow.
- SourceHut is entirely open-source. GitHub isn't, yet GitHub is somehow the standard platform for hosting open-source software. That seems contradictory to me.

**Comment by theavege** [comment]
Why don't you use GitLab?

**Comment by hannesbraun** [comment]
This one's more a matter of personal taste. Yet, GitLab doesn't have an email-driven workflow. It's bloated with features (at least for my taste) and quite often it was using a lot of CPU resources if I left a GitLab merge request tab open.
And while the community edition should be 100% FOSS, the enterprise edition isn't (right?), which is giving me mixed feelings about trusting GitLab in the long term.

In my opinion, Codeberg/Forgejo is a better alternative to GitHub if you prefer a GitHub/GitLab-like UI.

Would moving the project to SourceHut be a problem for you?

**Comment by theavege** [comment]
Moving will not problem for me.
I use Codeberg usually.
Thank you for your detailed answer.

**Pull request closed without merging**
